repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'main', '--branch', 'dev']
