version: '3.8'

x-common: &common
  container_name: luxonis-train
  env_file:
    - ${DOTENV_PATH}

x-gpu: &gpu
  <<: *common
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [ gpu ]

services:
  luxonis-train:
    <<: *common
    image: luxonis-train

  luxonis-train-gpu:
    <<: *gpu
    image: luxonis-train-gpu # TODO: create image that supports nvidia gpu