from enum import Enum


class HeadType(Enum):
    CLASSIFICATION = 1
    MULTI_LABEL_CLASSIFICATION = 2
    SEMANTIC_SEGMENTATION = 3
    INSTANCE_SEGMENTATION = 4
    OBJECT_DETECTION = 5
    KEYPOINT_DETECTION = 6
