# Example configuration for training a predefined detection model


use_rich_text: True

model:
  name: coco_detection
  predefined_model:
    name: DetectionModel
    params:
      use_neck: True

dataset:
  dataset_name: coco_test
  train_view: train
  val_view: train
  test_view: test

train:
  preprocessing:
    train_image_size: [&height 256, &width 320]
    keep_aspect_ratio: False
    normalize:
      active: True

  batch_size: 4
  epochs: &epochs 1
  num_workers: 4
  validation_interval: 1
  num_log_images: 8

  callbacks:
    - name: LearningRateMonitor
      params:
        logging_interval: step
    - name: EarlyStopping
      params:
        patience: 3
        monitor: val/loss
        mode: min
        verbose: true
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: SGD
    params:
      lr: 0.02
      momentum: 0.937
      nesterov: True
      weight_decay: 0.0005

  scheduler:
    name: CosineAnnealingLR
    params:
      T_max: *epochs
      eta_min: 0
