# Example configuration for training a predefined keypoint-detection model


use_rich_text: True

model:
  name: coco_keypoints
  predefined_model:
    name: KeypointDetectionModel

dataset:
  dataset_name: coco_test

train:
  preprocessing:
    train_image_size: [&height 256, &width 320]
    keep_aspect_ratio: False
    normalize:
      active: True

  batch_size: 4
  epochs: &epochs 1
  num_workers: 4
  validation_interval: 1
  num_log_images: 8

  callbacks:
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: SGD

  scheduler:
    name: ConstantLR
