logger:
  project_name: ml-ops-train
  save_directory: output
  is_tensorboard: True
  is_wandb: False
  is_mlflow: False

model:
  name: test_keypoint
  type: #YoloV6-n # uncomment this to use predefined model
  pretrained:
  params: # only take into account if using predefined model
    n_classes: 1

  backbone:
    name: EfficientRep
    pretrained:
    params:
      channels_list: [64, 128, 256, 512, 1024]
      num_repeats: [1, 6, 12, 18, 6]
      depth_mul: 0.33
      width_mul: 0.25

  neck:
    name: RepPANNeck
    params:
      channels_list: [256, 128, 128, 256, 256, 512]
      num_repeats: [12, 12, 12, 12]
      depth_mul: 0.33
      width_mul: 0.25

  heads:
    - name: YoloV7PoseHead
      params:
        n_classes: 1
        n_keypoints: 17
        n_layers: 3
      loss:
        name: YoloV7PoseLoss
        params:
          n_classes: 1
          n_keypoints: 17
          image_size: [320, 512]

dataset:
  local_path: coco-people

train:
  image_size: [320, 512]
  batch_size: 2
  accumulate_grad_batches: 2 # number of batches we do before doing backward pass
  epochs: 20
  n_workers: 2
  n_metrics: 2 # compute metrics on train set every n_metric epochs
  eval_interval: 1

  early_stopping:
    monitor: val_loss
    mode: min
    patience: 3

augmentations:
  # - name: Rotate # bug with albumentations dropping cropped bbox instances but not entire keypoint instances; https://github.com/albumentations-team/albumentations/blob/cb372736a0b7da362e5c2e23f3cce4304ddac402/albumentations/core/bbox_utils.py#L32
  #   params:
  #     limit: 90
  #     p: 1
  - name: Defocus
    params:

optimizer:
  name: Adam
  params:
    lr: 0.01
    weight_decay: 0.01

scheduler:
  name: LinearLR
  params:
    start_factor: 0.33

export:
  weights:
  save_directory: output_export
  image_size: [224, 224]
