# Example configuration for training a predefined segmentation model


use_rich_text: True

model:
  name: coco_segmentation
  predefined_model:
    name: SegmentationModel
    params:
      backbone: MicroNet
      task: binary

dataset:
  dataset_name: coco_test

train:
  preprocessing:
    train_image_size: [&height 256, &width 320]
    keep_aspect_ratio: False
    normalize:
      active: True

  batch_size: 4
  epochs: &epochs 200
  num_workers: 4
  validation_interval: 10
  num_log_images: 8

  callbacks:
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: SGD
    params:
      lr: 0.02

  scheduler:
    name: ConstantLR
