model:
  name: SimpleKeypoint

  backbone:
    name: EfficientRep

  neck:
    name: RepPANNeck

  heads:
    - name: KeypointBboxHead
      params:
        n_classes: null
      loss:
        name: KeypointBoxLoss

dataset:
  # team_id: # TODO
  # dataset_id: # TODO