model:
  name: SimpleKeypoint

  backbone:
    name: EfficientRep

  neck:
    name: RepPANNeck

  heads:
    - name: IKeypointHead
      params:
        n_classes: null
        n_keypoints: 17
      loss:
        name: YoloV7PoseLoss

dataset:
  team_id: # TODO
  dataset_id: # TODO