model:
  name: SimpleSegmentation
  
  backbone:
    name: ContextSpatial #ResNet18

  heads:
    - name: BiSeNetHead #SegmentationHead
      loss: 
        name: SigmoidFocalLoss

dataset:
  team_id: # TODO
  dataset_id: # TODO