model:
  name: SimpleDetection-Tuner
  type: yolov6-n
  params:
    n_classes: null

dataset:
  team_id: # TODO
  dataset_id: # TODO

tuner:
  params: # (key, value) pairs for tunning
    train.optimizers.optimizer.name_categorical: ["Adam", "SGD"]
    train.optimizers.optimizer.params.lr_float: [0.0001, 0.001]
    train.batch_size_int: [4, 4, 16]