model:
  name: SimpleKeypoint
  type:
  pretrained:

  backbone:
    name: EfficientRep
    pretrained:

  neck:
    name: RepPANNeck

  heads:
    - name: KeypointBoxHead
      params:
        n_classes: 1
        n_keypoints: 17
      loss:
        name: KeypointBoxLoss
        params:

dataset:
  team_id: # TODO
  dataset_id: # TODO
