export:
  weights: /home/klemen/luxonis/models/output/blue-vole-3/best_val_metric/val_map=0.0010_val_loss=3.4348_epoch=00_YoloV6-n.ckpt
  save_directory: output_export
  image_size: [128, 128]

model:
  name: YoloV6-n
  type: #YoloV6-n # uncomment this to use predefined model
  pretrained:
  params: # only take into account if using predefined model
    n_classes: 1

  backbone:
    name: EfficientRep
    pretrained:
    params:
      channels_list: [64, 128, 256, 512, 1024]
      num_repeats: [1, 6, 12, 18, 6]
      depth_mul: 0.33
      width_mul: 0.25

  neck:
    name: RepPANNeck
    params:
      channels_list: [256, 128, 128, 256, 256, 512]
      num_repeats: [12, 12, 12, 12]
      depth_mul: 0.33
      width_mul: 0.25

  heads:
    - name: YoloV6Head
      params:
        n_classes: 1
        n_layers: 3
        reg_max: 0
      loss: 
        name: YoloV6Loss
        params:
          n_classes: 1
          iou_type: siou

  # additional_heads:
    # - name: SegmentationHead
      # params:
        # n_classes: 2
      # loss: 
        # name: CrossEntropyLoss
        # params: