name: Build and deploy app image

on:
  push:
    branches:
      - docker
  workflow_dispatch:
env:
  PROJECT_ID: easyml-394818
  GAR_LOCATION: us-central1

jobs:
  push-store:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.6.0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          token_format: 'access_token'

      - uses: 'docker/login-action@v1'
        name: 'Docker login'
        with:
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
              
      - name: Get commit name
        id: commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
            
      - name: 'Build Inventory Image'
        run: |
          docker build --build-arg GITHUB_TOKEN=${{secrets.GHCR_PAT}} -f docker/Dockerfile . --tag $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/models/models:latest --tag $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/models/models:${{ steps.extract_branch.outputs.branch }}.${{ steps.commit.outputs.sha_short }}
          docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/models/models --all-tags