name: Autogenerate Requirements

on:
  pull_request:
    branches: [dev, main]
    paths:
      - 'pyproject.toml'

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run autogeneration script
      run: |
        python tools/autogenerate_requirements.py

    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git diff --quiet requirements.txt
        if [ $? -ne 0 ]; then
          git add requirements.txt
          git commit -m "[Automated] Updated requirements.txt"
          git push
        fi
